// <auto-generated />
using System;
using AnimalApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalApi.Migrations
{
    [DbContext(typeof(AnimalApiContext))]
    [Migration("20230609165336_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AdoptionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            AdoptionDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 1,
                            Breed = "Selberian Husky",
                            Name = "Tiger",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            AdoptionDate = new DateTime(2022, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 2,
                            Breed = "Bulldog",
                            Name = "Rexie",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            AdoptionDate = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 4,
                            Breed = "Goldern Retriever",
                            Name = "Matilda",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 4,
                            AdoptionDate = new DateTime(2023, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 5,
                            Breed = "British Shorthair",
                            Name = "Pip",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 5,
                            AdoptionDate = new DateTime(2023, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 3,
                            Breed = "Ragdoll",
                            Name = "Bartholomew",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 6,
                            AdoptionDate = new DateTime(2023, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 1,
                            Breed = "Birman",
                            Name = "Jasmine",
                            Species = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
